import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";

import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const guns = [
    { name: "Assault-Rifle", price: 1000 },
    { name: "Sniper", price: 2000 },
    { name: "Shotgun", price: 1500 },
    { name: "Revolver", price: 500 },
    { name: "Machine-Gun", price: 2500 },
    { name: "Pistol", price: 50 },
    { name: "RPG", price: 3000 },
    { name: "Laser-Gun", price: 3500 },
  ];

  const invt = [
    { name: "Medi-Kit", price: 500 },
    { name: "Molotov", price: 1000 },
    { name: "Grenade", price: 1500 },
    { name: "Knife", price: 2000 },
    { name: "Sword", price: 2500 },
    { name: "Armour", price: 3000 },
    { name: "C4", price: 3500 },
    { name: "Landmine", price: 4000 },
  ];

  const [gunsPrice, setGunsPrice] = React.useState(0);
  const [invtPrice, setInvtPrice] = React.useState(0);

  const [hydrated, setHydrated] = React.useState(false);

  React.useEffect(() => {
    setHydrated(true);
  }, []);
  if (!hydrated) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h3>Gunsmith.onion</h3>

        <div className={styles.cardHolder}>
          <div className={styles.card}>
            <h4>Select Guns Quantity</h4>

            <table>
              <thead>
                <tr>
                  <th>Guns</th>
                  <th>Price</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <br />
                </tr>
                {guns.map((gun, index) => (
                  <tr
                    key={index}
                    onClick={() => {
                      setGunsPrice(guns[index].price + gunsPrice);
                    }}
                  >
                    <td>
                      <button>-</button>
                      {gun.name}
                      <button>+</button>
                    </td>
                    <td>{gun.price}</td>
                  </tr>
                ))}

                <tr>
                  <br />
                </tr>

                <tr>
                  <td>Inventory Subtotal</td>
                  <td>${gunsPrice}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className={styles.card}>
            <h4>Select Inventory Quantity</h4>

            <table>
              <thead>
                <tr>
                  <th>Inventory</th>
                  <th>Price</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <br />
                </tr>
                {invt.map((inv, index) => (
                  <tr
                    key={index}
                    onClick={() => {
                      setInvtPrice(invt[index].price + invtPrice);
                    }}
                  >
                    <td>
                      <button>-</button>
                      {inv.name}
                      <button>+</button>
                    </td>

                    <td>{inv.price}</td>
                  </tr>
                ))}
                <tr>
                  <br />
                </tr>

                <tr>
                  <td>Inventory Subtotal</td>
                  <td>${invtPrice}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <button>Order Now</button>
      </main>
    </>
  );
}
